from fpdf import FPDF
from datetime import datetime

class AppointmentPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 20)
        self.set_text_color(0, 0, 0)
        self.cell(0, 12, 'MedBot AI Healthcare', 0, 1, 'C')

        self.set_font('Arial', 'I', 10)
        self.set_text_color(80, 80, 80)
        self.cell(0, 5, 'Appointment Confirmation Receipt', 0, 1, 'C')

        self.ln(5)
        self.set_draw_color(0, 0, 0)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(8)

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(0, 0, 0)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'Generated by MedBot AI', 0, 1, 'C')
        self.cell(0, 5, f'Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'C')


def generate_pdf(booking, output_file):
    pdf = AppointmentPDF()
    pdf.add_page()

    # Title
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'APPOINTMENT DETAILS', 0, 1, 'C')
    pdf.ln(5)

    # Booking ID
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(0, 10, f"Booking ID: {booking['Booking ID']}", 0, 1, 'C', True)
    pdf.ln(8)

    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0, 0, 0)

    details = [
        ('Patient Name', booking['Patient']),
        ('Age', str(booking['Age'])),
        ('Gender', booking['Gender']),
        ('Hospital', booking['Hospital']),
        ('Department', booking['Department']),
        ('Doctor', booking['Doctor']),
        ('Date', booking['Date']),
        ('Time', booking['Time'])
    ]

    for label, value in details:
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(60, 8, f'{label}:', 0, 0)
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, value, 0, 1)

    pdf.ln(10)

    pdf.output(output_file)
    print(f"PDF saved to {output_file}")
